name: Pull Request Validation
on: [pull_request]

jobs:
  xalendar_api_tests:
    name: Run tests Xalendar.Api.Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests for Xalendar.Api.Tests
      run: dotnet test src/Xalendar.Api.Tests/Xalendar.Api.Tests.csproj -v n /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Send report to codecov.io
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: 108d5d20-bca6-4e85-9bb6-fae56e78a84f

  xalendar_api:
    name: Build Xalendar.Api project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Install dependencies
      run: dotnet restore
      working-directory: 'src/'
    - name: Build
      run: dotnet build Xalendar.Api --configuration Release --no-restore
      working-directory: 'src/'

  xalendar_view_tests:
    name: Run tests Xalendar.View.Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests for Xalendar.View.Tests
      run: dotnet test src/Xalendar.View.Tests/Xalendar.View.Tests.csproj -v n /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Send report to codecov.io
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: 108d5d20-bca6-4e85-9bb6-fae56e78a84f

  xalendar_view:
    name: Build Xalendar.View project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core for Xalendar.View
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Install dependencies
      run: dotnet restore
      working-directory: 'src/'
    - name: Build
      run: dotnet build Xalendar.View --configuration Release --no-restore
      working-directory: 'src/'
